// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvwmaYuX6ZePiWM2A6uZs7kT0Qv4D3uFA',
    appId: '1:17581948445:web:01a122bf270bb3ac27d0f4',
    messagingSenderId: '17581948445',
    projectId: 'flutter-project-8f7a8',
    authDomain: 'flutter-project-8f7a8.firebaseapp.com',
    storageBucket: 'flutter-project-8f7a8.firebasestorage.app',
    measurementId: 'G-K9V7WKQNJV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY9CcV03DhmVpr2WTm_K7wVw20BEQ7Aws',
    appId: '1:17581948445:android:dea906be5af11e0327d0f4',
    messagingSenderId: '17581948445',
    projectId: 'flutter-project-8f7a8',
    storageBucket: 'flutter-project-8f7a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJJuaLQPB2IOUELDJ9U1_9A1fD81NXM7I',
    appId: '1:17581948445:ios:4a5e83dcdee6227227d0f4',
    messagingSenderId: '17581948445',
    projectId: 'flutter-project-8f7a8',
    storageBucket: 'flutter-project-8f7a8.firebasestorage.app',
    iosBundleId: 'com.example.aipdfnavigator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJJuaLQPB2IOUELDJ9U1_9A1fD81NXM7I',
    appId: '1:17581948445:ios:4a5e83dcdee6227227d0f4',
    messagingSenderId: '17581948445',
    projectId: 'flutter-project-8f7a8',
    storageBucket: 'flutter-project-8f7a8.firebasestorage.app',
    iosBundleId: 'com.example.aipdfnavigator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_ALnPGbWMyJ87WdbixF2ci3lMCsYh-So',
    appId: '1:17581948445:web:b698af89cf97a6fa27d0f4',
    messagingSenderId: '17581948445',
    projectId: 'flutter-project-8f7a8',
    authDomain: 'flutter-project-8f7a8.firebaseapp.com',
    storageBucket: 'flutter-project-8f7a8.firebasestorage.app',
    measurementId: 'G-ZHKL7JQMY9',
  );
}
